package com.example.material3_tests.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFFB52619)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFFFFDAD4)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF410000)
val md_theme_light_secondary = Color(color = 0xFF006874)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFF97F0FF)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF001F24)
val md_theme_light_tertiary = Color(color = 0xFF006874)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFF97F0FF)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF001F24)
val md_theme_light_error = Color(color = 0xFFBA1A1A)
val md_theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFF8FDFF)
val md_theme_light_onBackground = Color(color = 0xFF001F25)
val md_theme_light_surface = Color(color = 0xFFF8FDFF)
val md_theme_light_onSurface = Color(color = 0xFF001F25)
val md_theme_light_surfaceVariant = Color(color = 0xFFF5DDDA)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF534341)
val md_theme_light_outline = Color(color = 0xFF857370)
val md_theme_light_inverseOnSurface = Color(color = 0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(color = 0xFF00363F)
val md_theme_light_inversePrimary = Color(color = 0xFFFFB4A8)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFFB52619)
val md_theme_light_outlineVariant = Color(color = 0xFFD8C2BE)
val md_theme_light_scrim = Color(color = 0xFF000000)

val md_theme_dark_primary = Color(color = 0xFFFFB4A8)
val md_theme_dark_onPrimary = Color(color = 0xFF690000)
val md_theme_dark_primaryContainer = Color(color = 0xFF920703)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFFFFDAD4)
val md_theme_dark_secondary = Color(color = 0xFF4FD8EB)
val md_theme_dark_onSecondary = Color(color = 0xFF00363D)
val md_theme_dark_secondaryContainer = Color(color = 0xFF004F58)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFF97F0FF)
val md_theme_dark_tertiary = Color(color = 0xFF4FD8EB)
val md_theme_dark_onTertiary = Color(color = 0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFF97F0FF)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF001F25)
val md_theme_dark_onBackground = Color(color = 0xFFA6EEFF)
val md_theme_dark_surface = Color(color = 0xFF001F25)
val md_theme_dark_onSurface = Color(color = 0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(color = 0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFD8C2BE)
val md_theme_dark_outline = Color(color = 0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF001F25)
val md_theme_dark_inverseSurface = Color(color = 0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(color = 0xFFB52619)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFFFFB4A8)
val md_theme_dark_outlineVariant = Color(color = 0xFF534341)
val md_theme_dark_scrim = Color(color = 0xFF000000)


val seed = Color(color = 0xFF8B0000)